# This configuration has been moved to a different repository (jakopako/croncert-config) to
# separate the concert-specific configuration from the code. However, to have some examples
# and allow testing this file is not deleted from this repository.

global:
  user-agent: "jakopako/goskyr scan for croncert.ch"

writer:
  type: "file"
  # uri: "http://localhost:5000/api/events"
  # user: "croncert"
  # password: "croncert"
  filepath: "/home/dhondt/repos/goskyr/test-file.json"

# Scraper configs are grouped by city and cities are sorted alphabetically.
scrapers:
  ########
  # Basel
  ########
  - name: ParterreOne
    url: "https://www.parterre.net/de/musik-kultur/one-music/programm?category=1"
    item: "section.oneprog .upcomingprev"
    fields:
      static:
        - name: "location"
          value: "Parterre One"
        - name: "city"
          value: "Basel"
        - name: "type"
          value: "concert"
        - name: "sourceUrl"
          value: "https://www.parterre.net/de/musik-kultur/one-music/programm?category=1"
      dynamic:
        - name: "title"
          location:
            selector: ".smalltext h2"
        - name: "url"
          type: "url"
          location:
            selector: ".pic a"

  ##########
  # Bologna
  ##########
  - name: LocomotivClub # this field is used for logging and does not appear in the output of the scraper
    url: "https://www.locomotivclub.it/eventtype/calendario/"
    item: ".qt-item-event"
    fields:
      static:
        - name: "type"
          value: "concert"
        - name: "city"
          value: "Bologna"
        - name: "location"
          value: "LocomotivClub"
        - name: "sourceUrl"
          value: "https://www.locomotivclub.it/eventtype/calendario/"
      dynamic:
        - name: "title"
          location:
            selector: ".qt-text-shadow"
        - name: "comment"
          location:
            selector: ".qt-the-content div"
          can_be_empty: true
          on_subpage: "url"
        - name: "url"
          type: "url"
          location:
            selector: ".qt-text-shadow"
        - name: "date"
          type: "date"
          on_subpage: "url"
          components:
            - covers:
                day: true
                month: true
                year: true
              location:
                selector: ".qt-eventtable tr td"
                regex_extract:
                  exp: "Data:.*"
                child_index: -1 # -1 means: 'apply the regex until a child matches'
              layout: ["Data: 2 January 2006"]
            - covers:
                time: true
              location:
                selector: ".qt-eventtable tr td"
                node_index: 2
                regex_extract:
                  exp: "Inizio concerto: .*"
                child_index: -1 # -1 means: 'apply the regex until a child matches'
              layout: ["Inizio concerto: 3:04 pm"]
          date_location: "Europe/Berlin"
          date_language: "it_IT"
    filters:
      - field: "title"
        regex: ".*CANCELED.*"
        match: false
      - field: "title"
        regex: "ANNULLATO!.*"
        match: false
      - field: "title"
        regex: ".*Postponed.*"
        match: false
    paginator:
      location:
        selector: ".pagination .qt-btn-primary"
        node_index: -1
      max_pages: 4

  ##########
  # Brussels
  ##########
  - name: Botanique
    url: "https://botanique.be/en/concerts"
    item: ".views-content .event-type-concert"
    fields:
      static:
        - name: "type"
          value: "concert"
        - name: "city"
          value: "Brussels"
        - name: "location"
          value: "Botanique"
        - name: "sourceUrl"
          value: "https://botanique.be/en/concerts"
      dynamic:
        - name: "title"
          location:
            selector: ".node-type-event__title h2 a span"
        - name: "comment"
          can_be_empty: true
          location:
            selector: ".location-list li"
        - name: "url"
          type: "url"
          location:
            selector: ".node-type-event__title h2 a"
        - name: "date"
          type: "date"
          components:
            - covers:
                day: true
              location:
                selector: ".node-date__day"
              layout: ["02"]
            - covers:
                month: true
              location:
                selector: ".node-date__month"
              layout: ["Jan"]
            - covers:
                year: true
              location:
                selector: ".node-date__year"
              layout: ["2006"]
            - covers:
                time: true
              location:
                selector: ".node-type-event__timing"
                regex_extract:
                  exp: "[0-9]{2}:[0-9]{2}"
                child_index: -1
              layout: ["15:04"]
          date_location: "Europe/Berlin"
          date_language: "en_US"
    paginator:
      location:
        selector: ".pager__item a"
    filters:
      - field: "title"
        regex: ".*POSTPONED.*"
        match: false
      - field: "title"
        regex: ".*CANCELLED.*"
        match: false

  ##########
  # Leuven
  ##########
  - name: HetDepot
    url: "https://www.hetdepot.be/programma"
    item: ".calendar-item"
    fields:
      static:
        - name: "type"
          value: "concert"
        - name: "city"
          value: "Leuven"
        - name: "location"
          value: "HetDepot"
        - name: "sourceUrl"
          value: "https://www.hetdepot.be/programma"
      dynamic:
        - name: "title"
          location:
            selector: ".calendar-item__title"
        - name: "comment"
          location:
            selector: ".calendar-item__intro p"
          can_be_empty: true
        - name: "url"
          type: "url"
          location:
            selector: ".calendar-item__inner a"
        - name: "date"
          type: "date"
          on_subpage: "url"
          components:
            - covers:
                day: true
                month: true
                year: true
                time: true
              location:
                selector: ".concert__date time"
              layout: ["Monday 2 Jan 2006 - 15:04"]
          date_location: "Europe/Berlin"
          date_language: "nl_BE"
    paginator:
      location:
        selector: ".pager__item--next a"

  ##########
  # Munich
  ##########

  - name: Strom
    url: "https://strom-muc.de/"
    item: ".gdlr-event-item"
    exclude_with_selector:
      - ".cancelled-button"
      - ".coming-soon"
    fields:
      static:
        - name: "type"
          value: "concert"
        - name: "city"
          value: "Munich"
        - name: "location"
          value: "Strom"
        - name: "sourceUrl"
          value: "https://strom-muc.de/"
      dynamic:
        - name: "title"
          location:
            selector: ".event-title a"
        - name: "url"
          type: "url"
          location:
            selector: ".event-title a"
        - name: "date"
          type: "date"
          on_subpage: "url"
          components:
            - covers:
                day: true
                month: true
                year: true
              location:
                selector: ".gdlr-info-date"
                child_index: 1
                regex_extract:
                  exp: "([0-9]{2}\\.){2}[0-9]{4}"
              layout: ["02.01.2006"]
            - covers:
                time: true
              location:
                selector: ".gdlr-info-time"
                child_index: 1
                regex_extract:
                  exp: "[0-9]{2}(\\.|:)[0-9]{2}"
                  index: -1
              layout: ["15.04", "15:04"]
          date_location: "Europe/Berlin"

  - name: Muffatwerk
    url: "https://www.muffatwerk.de/de/events/concert"
    item: ".row .event"
    fields:
      static:
        - name: "type"
          value: "concert"
        - name: "city"
          value: "Munich"
        - name: "sourceUrl"
          value: "https://www.muffatwerk.de/de/events/concert"
      dynamic:
        - name: "title"
          location:
            selector: ".hover-in .center span"
        - name: "url"
          type: "url"
          location:
            selector: ".hover-in .right a"
        - name: "location"
          on_subpage: "url"
          location:
            selector: ".entry-info"
            child_index: 10
            regex_extract:
              exp: "[^:(]+"
              index: 1
        - name: "date"
          type: "date"
          components:
            - covers:
                day: true
                month: true
              location:
                selector: ".hover-in .center"
                child_index: -1
                regex_extract:
                  exp: "([0-9]{2}\\.){2}"
              layout: ["02.01."]
            - covers:
                year: true
              location:
                selector: ".date"
                child_index: 4
                regex_extract:
                  exp: "[0-9]{2}"
              layout: ["06"] # the whitespace in this string is a tab.
            - covers:
                time: true
              location:
                selector: ".hover-in .center"
                child_index: -1
                regex_extract:
                  exp: "[0-9]{2}:[0-9]{2}"
              layout: ["15:04"]
          date_location: "Europe/Berlin"
    filters:
      - field: "location"
        regex: "Zenith" # duplicate (also present on Motorworld website)
        match: false
      - field: "location"
        regex: "Strom" # duplicate
        match: false
      - field: "location"
        regex: "Tonhalle" # duplicate
        match: false
      - field: "location"
        regex: "TonHalle" # duplicate
        match: false

  #########
  # Vienna
  #########
  - name: Flex
    url: "http://flex.at/flex_frontend/index.php?selected=programm"
    item: "#programmWatchList .overview tr table"
    fields:
      static:
        - name: "location"
          value: "Flex"
        - name: "city"
          value: "Vienna"
        - name: "type"
          value: "concert"
        - name: "sourceUrl"
          value: "http://flex.at/flex_frontend/index.php?selected=programm"
      dynamic:
        - name: "title"
          location:
            selector: ".watchListInfo a"
            child_index: 2
        - name: "comment"
          location:
            selector: ".contentBoldYellow"
        - name: "url"
          type: "url"
          location:
            selector: ".watchListInfo a"
        - name: "date"
          type: "date"
          components:
            - covers:
                day: true
                month: true
                year: true
              location:
                selector: ".contentBoldWhite a"
              layout: ["02.01.2006"]
            - covers:
                time: true
              location:
                selector: ".watchListInfo a"
                regex_extract:
                  exp: "[0-9]{2}:[0-9]{2}"
              layout: ["15:04"]
          date_location: "Europe/Berlin"

  #########
  # Zurich
  #########
  - name: Sender
    url: "https://gds.fm/SENDER"
    item: ".event-list__item"
    fields:
      static:
        - name: "location"
          value: "Sender"
        - name: "city"
          value: "Zurich"
        - name: "type"
          value: "concert"
        - name: "sourceUrl"
          value: "https://gds.fm/SENDER"
      dynamic:
        - name: "title"
          location:
            selector: ".event-preview__title"
        - name: "comment"
          location:
            selector: ".event-detail__content div p"
            max_length: 200
          on_subpage: "url"
          can_be_empty: true
        - name: "url"
          type: "url"
          location:
            selector: "" # An empty string means that we look in the event node itself for an href
        - name: "date"
          type: "date"
          components:
            - covers:
                day: true
                month: true
                year: true
                time: true
              location:
                selector: ".event-preview__date-long"
              layout: ["January 02, 2006, 03:04 PM"]
          date_location: "GMT"
          date_language: "en_US"

  - name: ElLokal
    url: "http://www.ellokal.ch/?lang=de&details=9"
    item: "#maincontent > .commingupEventsList_0,.commingupEventsList_1"
    fields:
      static:
        - name: "location"
          value: "ElLokal"
        - name: "city"
          value: "Zurich"
        - name: "type"
          value: "concert"
        - name: "sourceUrl"
          value: "http://www.ellokal.ch/?lang=de&details=9"
      dynamic:
        - name: "title"
          location:
            selector: ".commingupEventsList_block5 a"
        - name: "comment"
          location:
            selector: ".concertStyleNew .concertDetails"
          on_subpage: "url"
          can_be_empty: true
        - name: "url"
          type: "url"
          location:
            selector: ".commingupEventsList_block5 a"
          relative: true
        - name: "date"
          type: "date"
          components:
            - covers:
                day: true
              location:
                selector: ".commingupEventsList_block2"
              layout: ["02. "]
            - covers:
                month: true
              location:
                selector: ".commingupEventsList_block3"
              layout: ["January"]
            - covers:
                time: true
              location:
                selector: ".commingupEventsList_block4"
              layout: ["15Uhr04"]
          date_location: "Europe/Berlin"
          date_language: "de_DE"

  - name: Komplex457
    url: "https://komplex-457.ch/event/"
    item: ".portfolio"
    fields:
      static:
        - name: "location"
          value: "Komplex457"
        - name: "city"
          value: "Zurich"
        - name: "type"
          value: "concert"
        - name: "sourceUrl"
          value: "https://komplex-457.ch/event/"
      dynamic:
        - name: "title"
          location:
            selector: ".av-masonry-entry-title"
        - name: "url"
          type: "url"
          location:
            selector: ""
        - name: "date"
          type: "date"
          on_subpage: "url"
          components:
            - covers:
                day: true
                month: true
                year: true
              location:
                selector: ".iconbox_content_container p"
                node_index: 0
                entire_subtree: true
                regex_extract:
                  exp: "[0-9]{2}\\.[0-9]{2}\\.[0-9]{4}"
              layout: ["02.01.2006"]
            - covers:
                time: true
              location:
                selector: ".iconbox_content_container p"
                node_index: 3
                regex_extract:
                  exp: "[0-9]{1,2}:[0-9]{2}"
              layout: ["15:04"]
          date_location: "Europe/Berlin"
