min_occurrences: 10
distinct_values: true
labler:
  type: "local-ml" # options: local-ml, remote-llm
  model_path: "../croncert-config/concert-20230509-mod" # only for local-random-forest
  words_dir: "../croncert-config/word-list" # only for local-random-forest
# fetcher:
#   type: "dynamic"
#   page_load_wait_ms: 2000ยง
